apiVersion: v1
kind: Service
metadata:
  labels:
    app: jobs
  name: jobs
  namespace: {{ .Release.Namespace }}
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8123
  selector:
    app: jobs
  sessionAffinity: None
  type: ClusterIP
