kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: log-reader
  namespace: {{ .Release.Namespace }} 
rules:
  - verbs:
      - '*'
    apiGroups:
      - serving.knative.dev
    resources:
      - services
  - verbs:
      - '*'
    apiGroups:
      - getambassador.io
    resources:
      - mappings
  - verbs: ["get", "list", "watch"]
    apiGroups: ["serving.knative.dev"]
    resources:
      - pods
      - pods/log
  - verbs: ["get", "list", "watch"]
    apiGroups: [""]
    resources:
      - pods
      - pods/log
