kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: log-reader
  namespace: {{ .Release.Namespace }} 
subjects:
- kind: ServiceAccount
  name: model-deployer
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: log-reader
  apiGroup: rbac.authorization.k8s.io
