apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: models
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Release.Namespace }}.badgerdoc.com
  connect_timeout_ms: 30000
  idle_timeout_ms: 50000
  prefix: /api/v1/models/
  service: models
  timeout_ms: 30000
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: models-internal
  namespace: {{ .Release.Namespace }}
spec:
  host: ambassador
  connect_timeout_ms: 30000
  idle_timeout_ms: 50000
  prefix: /api/v1/models/
  service: models
  timeout_ms: 30000
