apiVersion: v1
kind: Service
metadata:
  labels:
    app: models
  name: models
  namespace: {{ .Release.Namespace }}
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: models
  sessionAffinity: None
  type: ClusterIP
