networks:
  app-network:
    driver: bridge

services:
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - app-network


  web:
    build:
      context: .
      target: build
    stdin_open: true
    tty: true
    depends_on:
      - minio
    networks:
      - app-network
