all:
  hosts:
    node1:
      ansible_host: 172.31.32.217
      ip: 172.31.32.217
      access_ip: 172.31.32.217
      ansible_user: centos
      ansible_ssh_private_key_file: ~/.ssh/badgerdoc
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -q bastion_doc"'
    node2:
      ansible_host: 172.31.11.4
      ip: 172.31.11.4
      access_ip: 172.31.11.4
      ansible_user: centos
      ansible_ssh_private_key_file: ~/.ssh/badgerdoc
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -q bastion_doc"'
    node3:
      ansible_host: 172.31.43.63
      ip: 172.31.43.63
      access_ip: 172.31.43.63
      ansible_user: centos
      ansible_ssh_private_key_file: ~/.ssh/badgerdoc
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -q bastion_doc"'
    node4:
      ansible_host: 172.31.14.55
      ip: 172.31.14.55
      access_ip: 172.31.14.55
      ansible_user: centos
      ansible_ssh_private_key_file: ~/.ssh/badgerdoc
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -q bastion_doc"'    
  children:
    kube_control_plane:
      hosts:
        node3:
        node4:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
