apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: dev2
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      name: api
      protocol: TCP
      targetPort: 9000
    - port: 9001
      name: console
      protocol: TCP
      targetPort: 9001
  selector:
    app: minio
