apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: dev2
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_DB
          value: "models"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: superUserPassword
        - name: POSTGRES_USER
          value: admin
        ports:
        - containerPort: 5432
