apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev2
  name: model-deploy-role
rules:
- apiGroups: ["serving.knative.dev"]
  resources: ["services"]
  verbs: ["*"]
- apiGroups: ["getambassador.io"]
  resources: ["mappings"]
  verbs: ["*"]
